#ifndef OPENCL_INITIALIZER_HPP
#define OPENCL_INITIALIZER_HPP

#include "opencl.hpp"

#define OPENCL_INITIALIZER_PROFILE 0 >> 1
#define OPENCL_INITIALIZER_OUT_OF_ORDER 1 >> 1
#define OPENCL_INITIALIZER_USE_SOURCE 2 >> 1
#define OPENCL_INITIALIZER_CREATE_BINARY 3 >> 1
#define OPENCL_INITIALIZER_USE_BINARY 4 >> 1

#endif